### ISSUE TITLE
"Game is Starting" text remains on screen even after the game has started

### ISSUE THREAD

**Issue by yodelingllama** [FyuriStudios/SFG#13]
When two players join the server, if the game starts within a small window of the second player joining, the second player's screen will have "Game is Starting" displayed across it in big red letters.

**Comment by BLehrer99** [comment]
I think this is resolved but I'm gonna keep it open for now

**Comment by yodelingllama** [comment]
There's a new issue related to this: The p5 canvas stays superimposed over the stage and makes the stage noninteractive.
